neuro/items/urls.py
from django.urls import path
from . import views


app_name = 'items'

urlpatterns = [
    path('', views.index, name='index'),

    path('ranged/', views.ranged_all, name='all_ranged'),
    path('ranged/random/', views.randomized_ranged_weapons, name='random_ranged'),

    path('ranged/detail/<pk>', views.RangedDetailView.as_view(), name='detail_ranged'),

    path('ammo/', views.ammo_all, name='all_ammo'),
    path('ammo/random/', views.randomized_ammo, name='random_ammo'),
    path('ammo/detail/<pk>', views.AmmoDetailView.as_view(), name='detail_ammo'),

]

neuro/neuro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

neuro/items/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
import random
from django.db import models


class Difficulty(models.Model):
    id = models.TextField(primary_key=True)
    name = models.TextField()
    range = models.IntegerField()
    modifier = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'difficulty'

    def __str__(self) -> str :
        return self.name


class Damage(models.Model):
    id = models.TextField(unique=True)
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    symbol = models.TextField(primary_key=True)
    effect_on_target = models.TextField(blank=True, null=True)
    flat_modifier = models.IntegerField()
    pain_modifier = models.IntegerField()
    head_description = models.TextField(blank=True, null=True)
    torso_description = models.TextField(blank=True, null=True)
    r_arm_description = models.TextField(blank=True, null=True)
    l_arm_description = models.TextField(blank=True, null=True)
    leg_description = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'damage'

    def __str__(self) -> str :
        return self.name


class Weapon(models.Model):
    id_code = models.TextField(primary_key=True)
    name = models.TextField()
    description = models.TextField()
    modifier_10m = models.IntegerField(blank=True, null=True)
    modifier_20m = models.IntegerField(blank=True, null=True)
    modifier_30m = models.IntegerField(blank=True, null=True)
    modifier_40m = models.IntegerField(blank=True, null=True)
    modifier_60m = models.IntegerField(blank=True, null=True)
    modifier_80m = models.IntegerField(blank=True, null=True)
    modifier_100m = models.IntegerField(blank=True, null=True)
    modifier_150m = models.IntegerField(blank=True, null=True)
    modifier_200m = models.IntegerField(blank=True, null=True)
    modifier_250m = models.IntegerField(blank=True, null=True)
    modifier_300m = models.IntegerField(blank=True, null=True)
    modifier_400m = models.IntegerField(blank=True, null=True)
    modifier_600m = models.IntegerField(blank=True, null=True)
    modifier_1000m = models.IntegerField(blank=True, null=True)
    modifier_1500m = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'weapon'

    def __str__(self) -> str :
        return self.name


class Ammo(models.Model):
    id_code = models.TextField(primary_key=True)
    ammo_symbol = models.TextField()
    name = models.TextField()
    price = models.IntegerField()
    availability = models.IntegerField()
    crafting_difficulty = models.ForeignKey('Difficulty', on_delete=models.CASCADE, db_column='crafting_difficulty')
    description = models.TextField(blank=True, null=True)
    effect = models.TextField(blank=True, null=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="ammo", default="placeholder.png")
    weight = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'ammo'

    def __str__(self) -> str :
        return self.name

    def randomizer() -> list:  
        ammunition = Ammo.objects.all()
        list_of_ammo = []
        for ammo in ammunition:
            rand_num = random.randrange(0, 100)
            if ammo.availability >= rand_num:
                list_of_ammo.append(ammo)
        return list_of_ammo


class Ranged(models.Model):
    id_code = models.TextField(primary_key=True)
    name = models.TextField()
    weapon_class = models.ForeignKey('Weapon', on_delete=models.CASCADE, db_column='weapon_class')
    ammo = models.ForeignKey(Ammo, models.DO_NOTHING, db_column='ammo')
    magazine = models.IntegerField()
    misfire_roll = models.IntegerField()
    celnosc_w_procentach = models.IntegerField(blank=True, null=True)
    zasieg = models.IntegerField(blank=True, null=True)
    fire_rate = models.IntegerField(blank=True, null=True)
    attack_type = models.TextField(blank=True, null=True)
    reload = models.IntegerField(blank=True, null=True)
    punkty_przebicia = models.IntegerField()
    damage = models.ForeignKey(Damage, on_delete=models.CASCADE, db_column='damage')
    strength = models.IntegerField(blank=True, null=True)
    holster = models.IntegerField()
    price = models.IntegerField()
    availability = models.IntegerField()
    actions = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="ranged", default="placeholder.png")

    class Meta:
        managed = True
        db_table = 'ranged'

    def __str__(self) -> str :
        return self.name

    def randomizer() -> list:  
        guns = Ranged.objects.all()
        list_of_guns = []

        for gun in guns:
            rand_num = random.randrange(0, 100)
            if gun.availability >= rand_num:
                list_of_guns.append(gun)
                print(gun)
        return list_of_guns

neuro/items/views.py
import random

from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView

from .models import Ranged, Ammo
from .filters import RangedFilter

def index(request):
    return render(request, 'items/index.html')


def ranged_all(request):
    guns = Ranged.objects.all()
    my_filter = RangedFilter(request.GET, queryset=guns)
    guns = my_filter.qs
    
    page = request.GET.get('page', 1)
    paginator = Paginator(guns, 10)
    page_range = paginator.get_elided_page_range(number=page, on_each_side=3, on_ends=2)
    
    try:
        guns = paginator.page(page)
    except PageNotAnInteger:
        guns = paginator.page(1)
    except EmptyPage:
        guns = paginator.page(paginator.num_pages)
    
    context = {'list_of_guns': guns, 'my_filter': my_filter}
    return render(request, 'items/all_ranged.html', context)


def randomized_ranged_weapons(request):
    guns = Ranged.randomizer()
    return render(request, 'items/randomizer_weapon.html', {"list_of_guns" : guns})


class RangedDetailView(DetailView):
    template_name = 'items/detail_ranged.html'
    model = Ranged


def ammo_all(request):
    ammo = Ammo.objects.all()
    context = {'list_of_ammo': ammo}
    return render(request, 'items/all_ammo.html', context)


def randomized_ammo(request):
    ammunition = Ammo.randomizer()
    return render(request, 'items/randomizer_ammo.html', {"list_of_ammo" : ammunition})


class AmmoDetailView(DetailView):
    template_name = 'items/detail_ammo.html'
    model = Ammo

neuro/items/templates/items/all_ammo.html
{% extends 'items/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section class="s1">
    <div class="main-container">
        <div class="greeting-wrapper">
            Cała amunicja w bazie:
        </div>

        <div class="randomizer">
            To randomizer -> <a href="{% url 'items:random_ammo'%}" class="generate-btn" type="button"
                style=>Ammo Randomizer</a>
        </div>

        <div class="page-wrapper">
            <div class="search-wrapper">
                <form class='nav-wrapper' id="searchForm" method="GET">
                    {{my_filter.form|crispy}}
                    <input id="submit-button" type="submit" value="search">
                </form>
            </div>

<div class="item-wrapper">
    {% for ammo in list_of_ammo %}
    <div>
        <div class="item">
            <img class="thumbnail" src="{{ ammo.thumbnail.url }} ">
            <div class="item-preview">
                <h4 class="item-title">{{ammo.name}}</h4>
                <h4 class="item-addition">craft: {{ ammo.crafting_difficulty}}</h4>
                <p class="item-intro">{{ammo.description|slice:":100"}} </p>

                <a id="item-link" class="btn btn-info" href="{% url 'items:detail_ammo' ammo.id_code %}">Read
                    more</a>
                <h4 class="item-price">cena:
                    <strong>{{ammo.price}}</strong>
                </h4>
                <hr>
            </div>
        </div>
    </div>

    {% empty %}
    <h3> No ammo yet... </h3>
    {% endfor %}

</div>


{% endblock content %}

neuro/items/templates/items/all_ranged.html
{% extends 'items/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}



<section class="s1">
    <div class="main-container">
        <div class="greeting-wrapper">
            Wszystkie bronie w bazie:
        </div>

        <div class="randomizer">
            To randomizer -> <a href="{% url 'items:random_ranged'%}" class="generate-btn" type="button"
                style=>Randomizer</a>
        </div>

        <div class="page-wrapper">
            <div class="search-wrapper">
                <form class='nav-wrapper' id="searchForm" method="GET">
                    {{my_filter.form|crispy}}
                    <input id="submit-button" type="submit" value="search">
                </form>
            </div>

            <div class="item-wrapper">
                {% for ranged in list_of_guns %}
                <div>
                    <div class="item">
                        <img class="thumbnail" src="{{ ranged.thumbnail.url }} ">
                        <div class="item-preview">
                            <h4 class="item-title">{{ranged.name}}</h4>
                            <h4 class="item-addition">typ: {{ ranged.weapon_class}}</h4>
                            <h4 class="item-addition">min budowa: {{ ranged.strength }}</h4>
                            <p class="item-intro">{{ranged.description|slice:":100"}} </p>

                            <a id="item-link" class="btn btn-info"
                                href="{% url 'items:detail_ranged' ranged.id_code %}">Read more</a>
                            <h4 class="item-price"">cena:<strong>{{ranged.price}}</strong></h4>
        
                                {% comment %} {% if request.user.is_authenticated %}
                                <a id=" post-link" href="{% url 'update_post' post.slug %}">Edit</a>
                                <a id="post-link" href="{% url 'delete_post' post.slug %}">Delete</a>
                                {% endif %}

                                <hr>
                                {% for tag in post.tags.all %}
                                <span class="tag">{{ tag }} </span>
                                {% endfor %} {% endcomment %}
                                <hr>
                        </div>
                    </div>
                </div>

                {% empty %}
                <h3> No weapons yet... </h3>
                {% endfor %}
            </div>
        </div>


        <!-- Pagination -->
        <ul class="page-indicator">
            {% if list_of_guns.has_previous %}
            <li class="page-item">
                <a data-page="{{list_of_guns.previous_page_number}}" class="page-link"
                    href="?page={{ list_of_guns.previous_page_number }}">&laquo;</a>
            </li>
            {% else %}
            <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
            {% endif %}

            {% for i in page_range|default_if_none:list_of_guns.paginator.get_elided_page_range %}
            {% if ranged.number == i %}
            <li class="page-item"><a class="active-page-link">{{i}}</a></li>
            {% else %}

            {% if i == ranged.paginator.ELLIPSIS %}
            <li class="page-item"><span class="page-link">{{ paginator.ELLIPSIS }}</span></li>
            {% else %}
            <li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
            {% endif %}
            {% endif %}
            {% endfor %}

            {% if list_of_guns.has_next %}
            <li class="page-item">
                <a data-page="{{list_of_guns.next_page_number}}" class="page-link"
                    href="?page={{ list_of_guns.next_page_number }}">&raquo;</a>
            </li>
            {% else %}
            <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
    </div>
    <!--end of Pagination-->


    </div>
</section>

<script type="text/javascript">
    let searchForm = document.getElementById('searchForm')
    let pageLinks = document.getElementsByClassName('page-link')

    for (var i = 0; pageLinks.length; i++) {

        pageLinks[i].addEventListener('click', function (e) {
            e.preventDefault()
            let page = this.dataset.page
            console.log('Page:', page)
            searchForm.innerHTML += `<input value="${page}" name="page" hidden>`
            searchForm.submit()
        })
    }
</script>
{% endblock content %}

neuro/items/templates/items/detail_ammo.html
{% extends 'items/main.html' %}

{% block content %}

    <h1>Nazwa: {{ ammo.name }}</h1>
    <h1>Cena: {{ ammo.price }}</h1>
    <p>Dostępność: {{ ammo.availability }}</p>
    <p>Opis: {{ ammo.description }}</p>
    <p>Trudność produkcji: {{ ammo.crafting_difficulty }}</p>
    <p>Efekt: {{ ammo.effect }}</p>
    <p>Masa: {{ ammo.weight }}</p>
    <p>Image: {{ ammo.image }}</p>

{% endblock content %}

neuro/items/templates/items/detail_ranged.html
{% extends 'items/main.html' %}

{% block content %}

    <h1>Nazwa: {{ ranged.name }}</h1>
    <h1>Cena: {{ ranged.price }}</h1>
    <h2>Typ: {{ ranged.weapon_class }}</h2>
    <p>Amunicja: {{ ranged.ammo }}</p>
    <p>Pojemność magazynka: {{ ranged.magazine }}</p>
    <p>Zacięcie: {{ ranged.misfire_roll }}</p>
    <p>Celność w %: {{ ranged.celnosc_w_procentach }}</p>
    <p>Zasięg: {{ ranged.zasieg }}</p>
    <p>Szybkostrzelność: {{ ranged.fire_rate }}</p>
    <p>Typ ataku: {{ ranged.attack_type }}</p>
    <p>Czas przeładowania: {{ ranged.reload }}</p>
    <p>Punkty przebicia: {{ ranged.punkty_przebicia }}</p>
    <p>Obrażenia: {{ ranged.damage }}</p>
    <p>Wymagana Budowa: {{ ranged.strength }}</p>
    <p>Czy poręczny: {{ ranged.holster }}</p>
    <p>Dostępność: {{ ranged.availability }}</p>
    <p>Akcje: {{ ranged.actions }}</p>
    <p>Opis: {{ ranged.description }}</p>

{% endblock content %}

neuro/items/templates/items/index.html
<!DOCTYPE html>
{% extends 'items/main.html' %}
{% load static %}

{% block content %}

<section class="s1">
    <div class="main-container">

        <div class="intro">
            Welcome to Neuroshima item filter
        </div>

        <p>Różne elementy tutaj będą wyświetlone - wraz z informacjami co i jak.</p>

        <p>Póki co jest zrobione:</p>
        <ul>
            <li>
                Wyświetlanie listy wszystkich broni w bazie:
                <a href="{% url 'items:all_ranged'%}">Tutaj</a>
            </li>
            <li>
                Wyświetlanie listy całej amunicji w bazie:
                <a href="{% url 'items:all_ammo'%}">Tutaj</a>
            </li>
            <li>
                Random filter broni:
                <a href="{% url 'items:random_ranged'%}">Tutaj</a>
            </li>
            <li>
                Random filter amunicji:
                <a href="{% url 'items:random_ammo'%}">Tutaj</a>
            </li>
            <li>Wyświetlanie szczegółowe broni</li>
            <li>Wyświetlanie szczegółowe amunicji</li>
        </ul>
    </div>
</section>
{% endblock %}

neuro/items/templates/items/main.html
<!DOCTYPE html>
{% load static %}
<html>

    <head>
        <title>Neuroshima Vault</title>

        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

    </head>

    <body>
        <div class="navbar">
            {% include 'items/navbar.html'%}
        </div>

        {% block content %}

        <!---- content goes here -->

        {% endblock content %}

        <!--    {% comment %} Below is usage of js changes in other inharitance of main {% endcomment %}-->

       <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    </body>
</html>

neuro/items/templates/items/navbar.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">

<section class="navbar">
    <div class='navigation'>
        <ul>
            <li data-mode="home" class='navbar_list' id="home">
                <a href="{% url 'items:index'%}">
                    <span class="icon">
                        <ion-icon name="skull-outline"></ion-icon>
                    </span>
                    <span class="text">Home</span>
                </a>
            </li>
            <li data-mode="ranged" class='navbar_list' id="ranged">
                <a href="{% url 'items:all_ranged'%}">
                    <span class="icon">
                        <ion-icon name="telescope-outline"></ion-icon>
                    </span>
                    <span class="text">Ranged</span>
                </a>
            </li>
            <li data-mode="ammo" class='navbar_list' id="ammo">
                <a href="{% url 'items:all_ammo' %}">
                    <span class="icon">
                        <ion-icon name="rocket-outline"></ion-icon>
                    </span>
                    <span class="text">Ammo</span>
                </a>
            </li>
            <li data-mode="junk" class='navbar_list' id="junk">
                <a href="#">
                    <span class="icon">
                        <ion-icon name="trash-outline"></ion-icon>
                    </span>
                    <span class="text">Junk</span>
                </a>
            </li>
            <li data-mode="data" class='navbar_list' id="data">
                <a href="#">
                    <span class="icon">
                        <ion-icon name="cog-outline"></ion-icon>
                    </span>
                    <span class="text">Data</span>
                </a>
            </li>
            <div class="indicator"></div>
        </ul>
    </div>

    <script type="text/javascript">
        let static = "{% static 'css' %}"
    </script>

    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</section>

neuro/items/templates/items/randomizer_ammo.html
{% extends 'items/main.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Ammunition RANDOMIZER</h1>

    <form id="searchForm" method="GET">
        <p>Rzut na dostępność wykonywany dla każdej pozycji osobno! </p>
        <input id="submit-button" type="submit" value="new generate">
    </form>

    {% if list_of_ammo %}
    <ul>
    {% for ammo in list_of_ammo %}

        <li>
            {{ ammo.name }} - cena w gamblach: {{ ammo.price }}
            <a id="" href="{% url 'items:detail_ammo' ammo.id_code %}">Read more</a>
        </li>

        {% endfor %}
    </ul>
    {% else %}
        <p>No ammunition is available.</p>
    {% endif %}

{% endblock content %}

neuro/items/templates/items/randomizer_test.html
{% load crispy_forms_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Randomizer - test </title>
</head>
<body>
    <h1>RANDOMIZER TEST</h1>

    <form id="searchForm" method="GET">
        <p>Rzut na dostępność wykonywany dla każdej pozycji osobno! </p>
        <input id="submit-button" type="submit" value="new generate">
    </form>

    {% if list_of_guns %}
    <ul>
    {% for ranged in list_of_guns %}

        <li>{{ ranged.name }} - cena w gamblach: {{ ranged.price }} --> avail: {{ ranged.availability }}</li>

        {% endfor %}
    </ul>
    {% else %}
        <p>No weapons are available.</p>
    {% endif %}
</body>
</html>

neuro/items/templates/items/randomizer_weapon.html
{% extends 'items/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section class="s1">

    <div class="main-container">
        <div class="greeting-wrapper">
            RANGED WEAPON RANDOMIZER

            <div class="randomizer">
                <form id="searchForm" method="GET">
                    <p>Rzut na dostępność wykonywany dla każdej pozycji osobno! </p>
                    <input class="generate-btn" id="submit-button" type="submit" value="Random generate">

                </form>

            </div>
        </div>
        <div>
            <button class="btn btn-primary test_button" ranged_name={{ ranged.name}} value="TEST PRZYCISK">
            </button>
            <p>{{ ranged.name}}
        </div>
        <div>

        </div>
        <div class="item-wrapper">
            
            {% for ranged in list_of_guns %}
            <div>
                <div class="item">
                    <img class="thumbnail" src="{{ ranged.thumbnail.url }} ">
                    <div class="item-preview">
                        <h4 class="item-title">{{ranged.name}}</h4>
                        <h4 class="item-addition">typ: {{ ranged.weapon_class}}</h4>
                        <h4 class="item-addition">min budowa: {{ ranged.strength }}</h4>
                        <p class="item-intro">{{ranged.description|slice:":100"}} </p>

                        <a id="item-link" class="btn btn-info"
                            href="{% url 'items:detail_ranged' ranged.id_code %}">Read
                            more</a>
                        <h4 class="item-price">cena:
                            <strong>{{ranged.price}}</strong>
                        </h4>
                        <hr>
                    </div>
                </div>
            </div>

            {% empty %}
            <h3> No weapons yet... </h3>
            {% endfor %}

        </div>

        
</section>
{% endblock content %}

neuro/items/templates/items/ranged_detail.html
{% extends 'items/main.html' %}

{% block content %}

    <h1>Nazwa: {{ ranged.name }}</h1>
    <h1>Cena: {{ ranged.price }}</h1>
    <h2>Typ: {{ ranged.weapon_class }}</h2>
    <p>Amunicja: {{ ranged.ammo }}</p>
    <p>Pojemność magazynka: {{ ranged.magazine }}</p>
    <p>Zacięcie: {{ ranged.misfire_roll }}</p>
    <p>Celność w %: {{ ranged.celnosc_w_procentach }}</p>
    <p>Zasięg: {{ ranged.zasieg }}</p>
    <p>Szybkostrzelność: {{ ranged.fire_rate }}</p>
    <p>Typ ataku: {{ ranged.attack_type }}</p>
    <p>Czas przeładowania: {{ ranged.reload }}</p>
    <p>Punkty przebicia: {{ ranged.punkty_przebicia }}</p>
    <p>Obrażenia: {{ ranged.damage }}</p>
    <p>Wymagana Budowa: {{ ranged.strength }}</p>
    <p>Czy poręczny: {{ ranged.holster }}</p>
    <p>Dostępność: {{ ranged.availability }}</p>
    <p>Akcje: {{ ranged.actions }}</p>
    <p>Opis: {{ ranged.description }}</p>

{% endblock content %}